# This workflow will install Python dependencies, run tests and lint with a
# variety of Python versions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        #py-version: [3.7, 3.8, 3.9]
        py-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.py-version }}
      uses: actions/setup-python@v2
      with:
        py-version: ${{ matrix.py-version }}
    - name: Setup environment variables
      run: echo "WFDT::$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_ENV
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi
    - name: Create package and install it
      run: |
        python setup.py sdist bdist_wheel
        python3 -m pip -v install dist/capirca*py3*.whl
        echo "whereis aclgen"
    - name: Generate policy output with current version
      run: |
        sudo apt update
        sudo apt install unzip zip
        aclgen --output_directory ./output/current --logtostderr
        mkdir -p ./output/dist
        cd ./output/current/ && \
          zip -r ../dist/capirca_output_files_${{ matrix.py-version }}_$WFDT.zip .
        ls -alh *
    - name: Upload generated policies
      uses: actions/upload-artifact@v2
      with:
        name: capirca_output_files_${{ matrix.py-version }}_$WFDT
        path: ./output/dist/capirca_output_files_${{ matrix.py-version }}_$WFDT.zip
