# This workflow will install Python dependencies, run tests and lint with a
# variety of Python versions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        #python-version: [3.7, 3.8, 3.9]
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi
    - name: Create package and install it
      run: |
        python setup.py sdist bdist_wheel
        ls -alh dist/*
        pwd
        ls -alh *
        echo "module install"
        python3 -m pip -v --log /tmp/pip.log install dist/capirca*py3*.whl
        echo "whereis aclgen"
        whereis aclgen
        echo "show log"
        cat /tmp/pip.log
    - name: Generate policy output
      run: |
        aclgen
        ls -alh *
