# This workflow will install Python dependencies, run tests and lint with a
# variety of Python versions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        #python-version: [3.7, 3.8, 3.9]
        python-version: [3.9]

    steps:
    - name: Checkout branch with changes
      uses: actions/checkout@v2
      with:
        path: current
    - name: Checkout master branch
      uses: actions/checkout@v2
      with:
        path: master
        ref: master
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup environment variables
      run: |
        mkdir -p artifacts
        echo "wfdt=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_ENV
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install unzip zip
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi
    - name: Perform end-to-end testing with current branch or pull request
      run: |
        cd current
        git status
        python setup.py sdist bdist_wheel
        python3 -m pip -v install dist/capirca*py3*.whl
        aclgen --output_directory ./output --logtostderr
        cd ./output/ && \
          zip -r ../../artifacts/capirca_output_${{ env.wfdt }}.zip .
        cd ..
        python3 -m pip -v uninstall -y capirca
    - name: Perform end-to-end testing with master branch
      run: |
        cd master
        git status
        python setup.py sdist bdist_wheel
        python3 -m pip -v install dist/capirca*py3*.whl
        aclgen --output_directory ./output --logtostderr
        python3 -m pip -v uninstall -y capirca
    - name: Compare output files between the branches
      run: |
        sudo npm install -g diff2html diff2html-cli
        diff2html --version
        diff -r current/output master/output | diff2html --input stdin --file ./artifacts/policy_diff.html
    - name: Upload generated policies
      uses: actions/upload-artifact@v2
      with:
        name: capirca_output_${{ matrix.python-version }}_${{ env.wfdt }}
        path: ./artifacts/capirca_output_${{ env.wfdt }}.zip
    - name: Upload policy differences
      uses: actions/upload-artifact@v2
      with:
        name: capirca_output_policy_diff
        path: ./artifacts/policy_diff.html
